import XCTest
@testable import SwizzleIMD

final class SwizzleIMDTests: XCTestCase {
    func testSIMD2() {
        let value = SIMD2(0, 1)
        XCTAssertEqual(value.xx,.init(0, 0))
        XCTAssertEqual(value.xy,.init(0, 1))
        XCTAssertEqual(value.yx,.init(1, 0))
        XCTAssertEqual(value.yy,.init(1, 1))
    }
    
    func testSIMD3_XYZtoSIMD2() {
        let value = SIMD3(0, 1, 2)
        XCTAssertEqual(value.xx,.init(0, 0))
        XCTAssertEqual(value.xy,.init(0, 1))
        XCTAssertEqual(value.xz,.init(0, 2))
        XCTAssertEqual(value.yx,.init(1, 0))
        XCTAssertEqual(value.yy,.init(1, 1))
        XCTAssertEqual(value.yz,.init(1, 2))
        XCTAssertEqual(value.zx,.init(2, 0))
        XCTAssertEqual(value.zy,.init(2, 1))
        XCTAssertEqual(value.zz,.init(2, 2))
    }
    
    func testSIMD3_RGBtoScalar() {
        let value = SIMD3(0, 1, 2)
        XCTAssertEqual(value.r, 0)
        XCTAssertEqual(value.g, 1)
        XCTAssertEqual(value.b, 2)
    }
    
    func testSIMD3_RGBtoSIMD2() {
        let value = SIMD3(0, 1, 2)
        XCTAssertEqual(value.rr,.init(0, 0))
        XCTAssertEqual(value.rg,.init(0, 1))
        XCTAssertEqual(value.rb,.init(0, 2))
        XCTAssertEqual(value.gr,.init(1, 0))
        XCTAssertEqual(value.gg,.init(1, 1))
        XCTAssertEqual(value.gb,.init(1, 2))
        XCTAssertEqual(value.br,.init(2, 0))
        XCTAssertEqual(value.bg,.init(2, 1))
        XCTAssertEqual(value.bb,.init(2, 2))
    }
    
    func testSIMD3_XYZ() {
        let value = SIMD3(0, 1, 2)
        XCTAssertEqual(value.xxx,.init(0, 0, 0))
        XCTAssertEqual(value.xxy,.init(0, 0, 1))
        XCTAssertEqual(value.xxz,.init(0, 0, 2))
        XCTAssertEqual(value.xyx,.init(0, 1, 0))
        XCTAssertEqual(value.xyy,.init(0, 1, 1))
        XCTAssertEqual(value.xyz,.init(0, 1, 2))
        XCTAssertEqual(value.xzx,.init(0, 2, 0))
        XCTAssertEqual(value.xzy,.init(0, 2, 1))
        XCTAssertEqual(value.xzz,.init(0, 2, 2))
        XCTAssertEqual(value.yxx,.init(1, 0, 0))
        XCTAssertEqual(value.yxy,.init(1, 0, 1))
        XCTAssertEqual(value.yxz,.init(1, 0, 2))
        XCTAssertEqual(value.yyx,.init(1, 1, 0))
        XCTAssertEqual(value.yyy,.init(1, 1, 1))
        XCTAssertEqual(value.yyz,.init(1, 1, 2))
        XCTAssertEqual(value.yzx,.init(1, 2, 0))
        XCTAssertEqual(value.yzy,.init(1, 2, 1))
        XCTAssertEqual(value.yzz,.init(1, 2, 2))
        XCTAssertEqual(value.zxx,.init(2, 0, 0))
        XCTAssertEqual(value.zxy,.init(2, 0, 1))
        XCTAssertEqual(value.zxz,.init(2, 0, 2))
        XCTAssertEqual(value.zyx,.init(2, 1, 0))
        XCTAssertEqual(value.zyy,.init(2, 1, 1))
        XCTAssertEqual(value.zyz,.init(2, 1, 2))
        XCTAssertEqual(value.zzx,.init(2, 2, 0))
        XCTAssertEqual(value.zzy,.init(2, 2, 1))
        XCTAssertEqual(value.zzz,.init(2, 2, 2))
    }
    
    func testSIMD3_RGB() {
        let value = SIMD3(0, 1, 2)
        XCTAssertEqual(value.rrr,.init(0, 0, 0))
        XCTAssertEqual(value.rrg,.init(0, 0, 1))
        XCTAssertEqual(value.rrb,.init(0, 0, 2))
        XCTAssertEqual(value.rgr,.init(0, 1, 0))
        XCTAssertEqual(value.rgg,.init(0, 1, 1))
        XCTAssertEqual(value.rgb,.init(0, 1, 2))
        XCTAssertEqual(value.rbr,.init(0, 2, 0))
        XCTAssertEqual(value.rbg,.init(0, 2, 1))
        XCTAssertEqual(value.rbb,.init(0, 2, 2))
        XCTAssertEqual(value.grr,.init(1, 0, 0))
        XCTAssertEqual(value.grg,.init(1, 0, 1))
        XCTAssertEqual(value.grb,.init(1, 0, 2))
        XCTAssertEqual(value.ggr,.init(1, 1, 0))
        XCTAssertEqual(value.ggg,.init(1, 1, 1))
        XCTAssertEqual(value.ggb,.init(1, 1, 2))
        XCTAssertEqual(value.gbr,.init(1, 2, 0))
        XCTAssertEqual(value.gbg,.init(1, 2, 1))
        XCTAssertEqual(value.gbb,.init(1, 2, 2))
        XCTAssertEqual(value.brr,.init(2, 0, 0))
        XCTAssertEqual(value.brg,.init(2, 0, 1))
        XCTAssertEqual(value.brb,.init(2, 0, 2))
        XCTAssertEqual(value.bgr,.init(2, 1, 0))
        XCTAssertEqual(value.bgg,.init(2, 1, 1))
        XCTAssertEqual(value.bgb,.init(2, 1, 2))
        XCTAssertEqual(value.bbr,.init(2, 2, 0))
        XCTAssertEqual(value.bbg,.init(2, 2, 1))
        XCTAssertEqual(value.bbb,.init(2, 2, 2))
    }
    
    func testSIMD4_RGBAtoScalar() {
        let value = SIMD4(0, 1, 2, 3)
        XCTAssertEqual(value.r, 0)
        XCTAssertEqual(value.g, 1)
        XCTAssertEqual(value.b, 2)
        XCTAssertEqual(value.a, 3)
    }
    
    func testSIMD4_XYZWtoSIMD2() {
        let value = SIMD4(0, 1, 2, 3)
        XCTAssertEqual(value.xx,.init(0, 0))
        XCTAssertEqual(value.xy,.init(0, 1))
        XCTAssertEqual(value.xz,.init(0, 2))
        XCTAssertEqual(value.xw,.init(0, 3))
        XCTAssertEqual(value.yx,.init(1, 0))
        XCTAssertEqual(value.yy,.init(1, 1))
        XCTAssertEqual(value.yz,.init(1, 2))
        XCTAssertEqual(value.yw,.init(1, 3))
        XCTAssertEqual(value.zx,.init(2, 0))
        XCTAssertEqual(value.zy,.init(2, 1))
        XCTAssertEqual(value.zz,.init(2, 2))
        XCTAssertEqual(value.zw,.init(2, 3))
        XCTAssertEqual(value.wx,.init(3, 0))
        XCTAssertEqual(value.wy,.init(3, 1))
        XCTAssertEqual(value.wz,.init(3, 2))
        XCTAssertEqual(value.ww,.init(3, 3))
    }
    
    func testSIMD4_RGBAtoSIMD2() {
        let value = SIMD4(0, 1, 2, 3)
        XCTAssertEqual(value.rr,.init(0, 0))
        XCTAssertEqual(value.rg,.init(0, 1))
        XCTAssertEqual(value.rb,.init(0, 2))
        XCTAssertEqual(value.ra,.init(0, 3))
        XCTAssertEqual(value.gr,.init(1, 0))
        XCTAssertEqual(value.gg,.init(1, 1))
        XCTAssertEqual(value.gb,.init(1, 2))
        XCTAssertEqual(value.ga,.init(1, 3))
        XCTAssertEqual(value.br,.init(2, 0))
        XCTAssertEqual(value.bg,.init(2, 1))
        XCTAssertEqual(value.bb,.init(2, 2))
        XCTAssertEqual(value.ba,.init(2, 3))
        XCTAssertEqual(value.ar,.init(3, 0))
        XCTAssertEqual(value.ag,.init(3, 1))
        XCTAssertEqual(value.ab,.init(3, 2))
        XCTAssertEqual(value.aa,.init(3, 3))
    }
    
    func testSIMD4_XYZWtoSIMD3() {
        let value = SIMD4(0, 1, 2, 3)
        XCTAssertEqual(value.xxx,.init(0, 0, 0))
        XCTAssertEqual(value.xxy,.init(0, 0, 1))
        XCTAssertEqual(value.xxz,.init(0, 0, 2))
        XCTAssertEqual(value.xxw,.init(0, 0, 3))
        XCTAssertEqual(value.xyx,.init(0, 1, 0))
        XCTAssertEqual(value.xyy,.init(0, 1, 1))
        XCTAssertEqual(value.xyz,.init(0, 1, 2))
        XCTAssertEqual(value.xyw,.init(0, 1, 3))
        XCTAssertEqual(value.xzx,.init(0, 2, 0))
        XCTAssertEqual(value.xzy,.init(0, 2, 1))
        XCTAssertEqual(value.xzz,.init(0, 2, 2))
        XCTAssertEqual(value.xzw,.init(0, 2, 3))
        XCTAssertEqual(value.xwx,.init(0, 3, 0))
        XCTAssertEqual(value.xwy,.init(0, 3, 1))
        XCTAssertEqual(value.xwz,.init(0, 3, 2))
        XCTAssertEqual(value.xww,.init(0, 3, 3))
        XCTAssertEqual(value.yxx,.init(1, 0, 0))
        XCTAssertEqual(value.yxy,.init(1, 0, 1))
        XCTAssertEqual(value.yxz,.init(1, 0, 2))
        XCTAssertEqual(value.yxw,.init(1, 0, 3))
        XCTAssertEqual(value.yyx,.init(1, 1, 0))
        XCTAssertEqual(value.yyy,.init(1, 1, 1))
        XCTAssertEqual(value.yyz,.init(1, 1, 2))
        XCTAssertEqual(value.yyw,.init(1, 1, 3))
        XCTAssertEqual(value.yzx,.init(1, 2, 0))
        XCTAssertEqual(value.yzy,.init(1, 2, 1))
        XCTAssertEqual(value.yzz,.init(1, 2, 2))
        XCTAssertEqual(value.yzw,.init(1, 2, 3))
        XCTAssertEqual(value.ywx,.init(1, 3, 0))
        XCTAssertEqual(value.ywy,.init(1, 3, 1))
        XCTAssertEqual(value.ywz,.init(1, 3, 2))
        XCTAssertEqual(value.yww,.init(1, 3, 3))
        XCTAssertEqual(value.zxx,.init(2, 0, 0))
        XCTAssertEqual(value.zxy,.init(2, 0, 1))
        XCTAssertEqual(value.zxz,.init(2, 0, 2))
        XCTAssertEqual(value.zxw,.init(2, 0, 3))
        XCTAssertEqual(value.zyx,.init(2, 1, 0))
        XCTAssertEqual(value.zyy,.init(2, 1, 1))
        XCTAssertEqual(value.zyz,.init(2, 1, 2))
        XCTAssertEqual(value.zyw,.init(2, 1, 3))
        XCTAssertEqual(value.zzx,.init(2, 2, 0))
        XCTAssertEqual(value.zzy,.init(2, 2, 1))
        XCTAssertEqual(value.zzz,.init(2, 2, 2))
        XCTAssertEqual(value.zzw,.init(2, 2, 3))
        XCTAssertEqual(value.zwx,.init(2, 3, 0))
        XCTAssertEqual(value.zwy,.init(2, 3, 1))
        XCTAssertEqual(value.zwz,.init(2, 3, 2))
        XCTAssertEqual(value.zww,.init(2, 3, 3))
        XCTAssertEqual(value.wxx,.init(3, 0, 0))
        XCTAssertEqual(value.wxy,.init(3, 0, 1))
        XCTAssertEqual(value.wxz,.init(3, 0, 2))
        XCTAssertEqual(value.wxw,.init(3, 0, 3))
        XCTAssertEqual(value.wyx,.init(3, 1, 0))
        XCTAssertEqual(value.wyy,.init(3, 1, 1))
        XCTAssertEqual(value.wyz,.init(3, 1, 2))
        XCTAssertEqual(value.wyw,.init(3, 1, 3))
        XCTAssertEqual(value.wzx,.init(3, 2, 0))
        XCTAssertEqual(value.wzy,.init(3, 2, 1))
        XCTAssertEqual(value.wzz,.init(3, 2, 2))
        XCTAssertEqual(value.wzw,.init(3, 2, 3))
        XCTAssertEqual(value.wwx,.init(3, 3, 0))
        XCTAssertEqual(value.wwy,.init(3, 3, 1))
        XCTAssertEqual(value.wwz,.init(3, 3, 2))
        XCTAssertEqual(value.www,.init(3, 3, 3))
    }
    
    func testSIMD4_RGBAtoSIMD3() {
        let value = SIMD4(0, 1, 2, 3)
        XCTAssertEqual(value.rrr,.init(0, 0, 0))
        XCTAssertEqual(value.rrg,.init(0, 0, 1))
        XCTAssertEqual(value.rrb,.init(0, 0, 2))
        XCTAssertEqual(value.rra,.init(0, 0, 3))
        XCTAssertEqual(value.rgr,.init(0, 1, 0))
        XCTAssertEqual(value.rgg,.init(0, 1, 1))
        XCTAssertEqual(value.rgb,.init(0, 1, 2))
        XCTAssertEqual(value.rga,.init(0, 1, 3))
        XCTAssertEqual(value.rbr,.init(0, 2, 0))
        XCTAssertEqual(value.rbg,.init(0, 2, 1))
        XCTAssertEqual(value.rbb,.init(0, 2, 2))
        XCTAssertEqual(value.rba,.init(0, 2, 3))
        XCTAssertEqual(value.rar,.init(0, 3, 0))
        XCTAssertEqual(value.rag,.init(0, 3, 1))
        XCTAssertEqual(value.rab,.init(0, 3, 2))
        XCTAssertEqual(value.raa,.init(0, 3, 3))
        XCTAssertEqual(value.grr,.init(1, 0, 0))
        XCTAssertEqual(value.grg,.init(1, 0, 1))
        XCTAssertEqual(value.grb,.init(1, 0, 2))
        XCTAssertEqual(value.gra,.init(1, 0, 3))
        XCTAssertEqual(value.ggr,.init(1, 1, 0))
        XCTAssertEqual(value.ggg,.init(1, 1, 1))
        XCTAssertEqual(value.ggb,.init(1, 1, 2))
        XCTAssertEqual(value.gga,.init(1, 1, 3))
        XCTAssertEqual(value.gbr,.init(1, 2, 0))
        XCTAssertEqual(value.gbg,.init(1, 2, 1))
        XCTAssertEqual(value.gbb,.init(1, 2, 2))
        XCTAssertEqual(value.gba,.init(1, 2, 3))
        XCTAssertEqual(value.gar,.init(1, 3, 0))
        XCTAssertEqual(value.gag,.init(1, 3, 1))
        XCTAssertEqual(value.gab,.init(1, 3, 2))
        XCTAssertEqual(value.gaa,.init(1, 3, 3))
        XCTAssertEqual(value.brr,.init(2, 0, 0))
        XCTAssertEqual(value.brg,.init(2, 0, 1))
        XCTAssertEqual(value.brb,.init(2, 0, 2))
        XCTAssertEqual(value.bra,.init(2, 0, 3))
        XCTAssertEqual(value.bgr,.init(2, 1, 0))
        XCTAssertEqual(value.bgg,.init(2, 1, 1))
        XCTAssertEqual(value.bgb,.init(2, 1, 2))
        XCTAssertEqual(value.bga,.init(2, 1, 3))
        XCTAssertEqual(value.bbr,.init(2, 2, 0))
        XCTAssertEqual(value.bbg,.init(2, 2, 1))
        XCTAssertEqual(value.bbb,.init(2, 2, 2))
        XCTAssertEqual(value.bba,.init(2, 2, 3))
        XCTAssertEqual(value.bar,.init(2, 3, 0))
        XCTAssertEqual(value.bag,.init(2, 3, 1))
        XCTAssertEqual(value.bab,.init(2, 3, 2))
        XCTAssertEqual(value.baa,.init(2, 3, 3))
        XCTAssertEqual(value.arr,.init(3, 0, 0))
        XCTAssertEqual(value.arg,.init(3, 0, 1))
        XCTAssertEqual(value.arb,.init(3, 0, 2))
        XCTAssertEqual(value.ara,.init(3, 0, 3))
        XCTAssertEqual(value.agr,.init(3, 1, 0))
        XCTAssertEqual(value.agg,.init(3, 1, 1))
        XCTAssertEqual(value.agb,.init(3, 1, 2))
        XCTAssertEqual(value.aga,.init(3, 1, 3))
        XCTAssertEqual(value.abr,.init(3, 2, 0))
        XCTAssertEqual(value.abg,.init(3, 2, 1))
        XCTAssertEqual(value.abb,.init(3, 2, 2))
        XCTAssertEqual(value.aba,.init(3, 2, 3))
        XCTAssertEqual(value.aar,.init(3, 3, 0))
        XCTAssertEqual(value.aag,.init(3, 3, 1))
        XCTAssertEqual(value.aab,.init(3, 3, 2))
        XCTAssertEqual(value.aaa,.init(3, 3, 3))
    }
    
    func testSIMD4_XYZW() {
        let value = SIMD4(0, 1, 2, 3)
        XCTAssertEqual(value.xxxx,.init(0, 0, 0, 0))
        XCTAssertEqual(value.xxxy,.init(0, 0, 0, 1))
        XCTAssertEqual(value.xxxz,.init(0, 0, 0, 2))
        XCTAssertEqual(value.xxxw,.init(0, 0, 0, 3))
        XCTAssertEqual(value.xxyx,.init(0, 0, 1, 0))
        XCTAssertEqual(value.xxyy,.init(0, 0, 1, 1))
        XCTAssertEqual(value.xxyz,.init(0, 0, 1, 2))
        XCTAssertEqual(value.xxyw,.init(0, 0, 1, 3))
        XCTAssertEqual(value.xxzx,.init(0, 0, 2, 0))
        XCTAssertEqual(value.xxzy,.init(0, 0, 2, 1))
        XCTAssertEqual(value.xxzz,.init(0, 0, 2, 2))
        XCTAssertEqual(value.xxzw,.init(0, 0, 2, 3))
        XCTAssertEqual(value.xxwx,.init(0, 0, 3, 0))
        XCTAssertEqual(value.xxwy,.init(0, 0, 3, 1))
        XCTAssertEqual(value.xxwz,.init(0, 0, 3, 2))
        XCTAssertEqual(value.xxww,.init(0, 0, 3, 3))
        XCTAssertEqual(value.xyxx,.init(0, 1, 0, 0))
        XCTAssertEqual(value.xyxy,.init(0, 1, 0, 1))
        XCTAssertEqual(value.xyxz,.init(0, 1, 0, 2))
        XCTAssertEqual(value.xyxw,.init(0, 1, 0, 3))
        XCTAssertEqual(value.xyyx,.init(0, 1, 1, 0))
        XCTAssertEqual(value.xyyy,.init(0, 1, 1, 1))
        XCTAssertEqual(value.xyyz,.init(0, 1, 1, 2))
        XCTAssertEqual(value.xyyw,.init(0, 1, 1, 3))
        XCTAssertEqual(value.xyzx,.init(0, 1, 2, 0))
        XCTAssertEqual(value.xyzy,.init(0, 1, 2, 1))
        XCTAssertEqual(value.xyzz,.init(0, 1, 2, 2))
        XCTAssertEqual(value.xyzw,.init(0, 1, 2, 3))
        XCTAssertEqual(value.xywx,.init(0, 1, 3, 0))
        XCTAssertEqual(value.xywy,.init(0, 1, 3, 1))
        XCTAssertEqual(value.xywz,.init(0, 1, 3, 2))
        XCTAssertEqual(value.xyww,.init(0, 1, 3, 3))
        XCTAssertEqual(value.xzxx,.init(0, 2, 0, 0))
        XCTAssertEqual(value.xzxy,.init(0, 2, 0, 1))
        XCTAssertEqual(value.xzxz,.init(0, 2, 0, 2))
        XCTAssertEqual(value.xzxw,.init(0, 2, 0, 3))
        XCTAssertEqual(value.xzyx,.init(0, 2, 1, 0))
        XCTAssertEqual(value.xzyy,.init(0, 2, 1, 1))
        XCTAssertEqual(value.xzyz,.init(0, 2, 1, 2))
        XCTAssertEqual(value.xzyw,.init(0, 2, 1, 3))
        XCTAssertEqual(value.xzzx,.init(0, 2, 2, 0))
        XCTAssertEqual(value.xzzy,.init(0, 2, 2, 1))
        XCTAssertEqual(value.xzzz,.init(0, 2, 2, 2))
        XCTAssertEqual(value.xzzw,.init(0, 2, 2, 3))
        XCTAssertEqual(value.xzwx,.init(0, 2, 3, 0))
        XCTAssertEqual(value.xzwy,.init(0, 2, 3, 1))
        XCTAssertEqual(value.xzwz,.init(0, 2, 3, 2))
        XCTAssertEqual(value.xzww,.init(0, 2, 3, 3))
        XCTAssertEqual(value.xwxx,.init(0, 3, 0, 0))
        XCTAssertEqual(value.xwxy,.init(0, 3, 0, 1))
        XCTAssertEqual(value.xwxz,.init(0, 3, 0, 2))
        XCTAssertEqual(value.xwxw,.init(0, 3, 0, 3))
        XCTAssertEqual(value.xwyx,.init(0, 3, 1, 0))
        XCTAssertEqual(value.xwyy,.init(0, 3, 1, 1))
        XCTAssertEqual(value.xwyz,.init(0, 3, 1, 2))
        XCTAssertEqual(value.xwyw,.init(0, 3, 1, 3))
        XCTAssertEqual(value.xwzx,.init(0, 3, 2, 0))
        XCTAssertEqual(value.xwzy,.init(0, 3, 2, 1))
        XCTAssertEqual(value.xwzz,.init(0, 3, 2, 2))
        XCTAssertEqual(value.xwzw,.init(0, 3, 2, 3))
        XCTAssertEqual(value.xwwx,.init(0, 3, 3, 0))
        XCTAssertEqual(value.xwwy,.init(0, 3, 3, 1))
        XCTAssertEqual(value.xwwz,.init(0, 3, 3, 2))
        XCTAssertEqual(value.xwww,.init(0, 3, 3, 3))
        XCTAssertEqual(value.yxxx,.init(1, 0, 0, 0))
        XCTAssertEqual(value.yxxy,.init(1, 0, 0, 1))
        XCTAssertEqual(value.yxxz,.init(1, 0, 0, 2))
        XCTAssertEqual(value.yxxw,.init(1, 0, 0, 3))
        XCTAssertEqual(value.yxyx,.init(1, 0, 1, 0))
        XCTAssertEqual(value.yxyy,.init(1, 0, 1, 1))
        XCTAssertEqual(value.yxyz,.init(1, 0, 1, 2))
        XCTAssertEqual(value.yxyw,.init(1, 0, 1, 3))
        XCTAssertEqual(value.yxzx,.init(1, 0, 2, 0))
        XCTAssertEqual(value.yxzy,.init(1, 0, 2, 1))
        XCTAssertEqual(value.yxzz,.init(1, 0, 2, 2))
        XCTAssertEqual(value.yxzw,.init(1, 0, 2, 3))
        XCTAssertEqual(value.yxwx,.init(1, 0, 3, 0))
        XCTAssertEqual(value.yxwy,.init(1, 0, 3, 1))
        XCTAssertEqual(value.yxwz,.init(1, 0, 3, 2))
        XCTAssertEqual(value.yxww,.init(1, 0, 3, 3))
        XCTAssertEqual(value.yyxx,.init(1, 1, 0, 0))
        XCTAssertEqual(value.yyxy,.init(1, 1, 0, 1))
        XCTAssertEqual(value.yyxz,.init(1, 1, 0, 2))
        XCTAssertEqual(value.yyxw,.init(1, 1, 0, 3))
        XCTAssertEqual(value.yyyx,.init(1, 1, 1, 0))
        XCTAssertEqual(value.yyyy,.init(1, 1, 1, 1))
        XCTAssertEqual(value.yyyz,.init(1, 1, 1, 2))
        XCTAssertEqual(value.yyyw,.init(1, 1, 1, 3))
        XCTAssertEqual(value.yyzx,.init(1, 1, 2, 0))
        XCTAssertEqual(value.yyzy,.init(1, 1, 2, 1))
        XCTAssertEqual(value.yyzz,.init(1, 1, 2, 2))
        XCTAssertEqual(value.yyzw,.init(1, 1, 2, 3))
        XCTAssertEqual(value.yywx,.init(1, 1, 3, 0))
        XCTAssertEqual(value.yywy,.init(1, 1, 3, 1))
        XCTAssertEqual(value.yywz,.init(1, 1, 3, 2))
        XCTAssertEqual(value.yyww,.init(1, 1, 3, 3))
        XCTAssertEqual(value.yzxx,.init(1, 2, 0, 0))
        XCTAssertEqual(value.yzxy,.init(1, 2, 0, 1))
        XCTAssertEqual(value.yzxz,.init(1, 2, 0, 2))
        XCTAssertEqual(value.yzxw,.init(1, 2, 0, 3))
        XCTAssertEqual(value.yzyx,.init(1, 2, 1, 0))
        XCTAssertEqual(value.yzyy,.init(1, 2, 1, 1))
        XCTAssertEqual(value.yzyz,.init(1, 2, 1, 2))
        XCTAssertEqual(value.yzyw,.init(1, 2, 1, 3))
        XCTAssertEqual(value.yzzx,.init(1, 2, 2, 0))
        XCTAssertEqual(value.yzzy,.init(1, 2, 2, 1))
        XCTAssertEqual(value.yzzz,.init(1, 2, 2, 2))
        XCTAssertEqual(value.yzzw,.init(1, 2, 2, 3))
        XCTAssertEqual(value.yzwx,.init(1, 2, 3, 0))
        XCTAssertEqual(value.yzwy,.init(1, 2, 3, 1))
        XCTAssertEqual(value.yzwz,.init(1, 2, 3, 2))
        XCTAssertEqual(value.yzww,.init(1, 2, 3, 3))
        XCTAssertEqual(value.ywxx,.init(1, 3, 0, 0))
        XCTAssertEqual(value.ywxy,.init(1, 3, 0, 1))
        XCTAssertEqual(value.ywxz,.init(1, 3, 0, 2))
        XCTAssertEqual(value.ywxw,.init(1, 3, 0, 3))
        XCTAssertEqual(value.ywyx,.init(1, 3, 1, 0))
        XCTAssertEqual(value.ywyy,.init(1, 3, 1, 1))
        XCTAssertEqual(value.ywyz,.init(1, 3, 1, 2))
        XCTAssertEqual(value.ywyw,.init(1, 3, 1, 3))
        XCTAssertEqual(value.ywzx,.init(1, 3, 2, 0))
        XCTAssertEqual(value.ywzy,.init(1, 3, 2, 1))
        XCTAssertEqual(value.ywzz,.init(1, 3, 2, 2))
        XCTAssertEqual(value.ywzw,.init(1, 3, 2, 3))
        XCTAssertEqual(value.ywwx,.init(1, 3, 3, 0))
        XCTAssertEqual(value.ywwy,.init(1, 3, 3, 1))
        XCTAssertEqual(value.ywwz,.init(1, 3, 3, 2))
        XCTAssertEqual(value.ywww,.init(1, 3, 3, 3))
        XCTAssertEqual(value.zxxx,.init(2, 0, 0, 0))
        XCTAssertEqual(value.zxxy,.init(2, 0, 0, 1))
        XCTAssertEqual(value.zxxz,.init(2, 0, 0, 2))
        XCTAssertEqual(value.zxxw,.init(2, 0, 0, 3))
        XCTAssertEqual(value.zxyx,.init(2, 0, 1, 0))
        XCTAssertEqual(value.zxyy,.init(2, 0, 1, 1))
        XCTAssertEqual(value.zxyz,.init(2, 0, 1, 2))
        XCTAssertEqual(value.zxyw,.init(2, 0, 1, 3))
        XCTAssertEqual(value.zxzx,.init(2, 0, 2, 0))
        XCTAssertEqual(value.zxzy,.init(2, 0, 2, 1))
        XCTAssertEqual(value.zxzz,.init(2, 0, 2, 2))
        XCTAssertEqual(value.zxzw,.init(2, 0, 2, 3))
        XCTAssertEqual(value.zxwx,.init(2, 0, 3, 0))
        XCTAssertEqual(value.zxwy,.init(2, 0, 3, 1))
        XCTAssertEqual(value.zxwz,.init(2, 0, 3, 2))
        XCTAssertEqual(value.zxww,.init(2, 0, 3, 3))
        XCTAssertEqual(value.zyxx,.init(2, 1, 0, 0))
        XCTAssertEqual(value.zyxy,.init(2, 1, 0, 1))
        XCTAssertEqual(value.zyxz,.init(2, 1, 0, 2))
        XCTAssertEqual(value.zyxw,.init(2, 1, 0, 3))
        XCTAssertEqual(value.zyyx,.init(2, 1, 1, 0))
        XCTAssertEqual(value.zyyy,.init(2, 1, 1, 1))
        XCTAssertEqual(value.zyyz,.init(2, 1, 1, 2))
        XCTAssertEqual(value.zyyw,.init(2, 1, 1, 3))
        XCTAssertEqual(value.zyzx,.init(2, 1, 2, 0))
        XCTAssertEqual(value.zyzy,.init(2, 1, 2, 1))
        XCTAssertEqual(value.zyzz,.init(2, 1, 2, 2))
        XCTAssertEqual(value.zyzw,.init(2, 1, 2, 3))
        XCTAssertEqual(value.zywx,.init(2, 1, 3, 0))
        XCTAssertEqual(value.zywy,.init(2, 1, 3, 1))
        XCTAssertEqual(value.zywz,.init(2, 1, 3, 2))
        XCTAssertEqual(value.zyww,.init(2, 1, 3, 3))
        XCTAssertEqual(value.zzxx,.init(2, 2, 0, 0))
        XCTAssertEqual(value.zzxy,.init(2, 2, 0, 1))
        XCTAssertEqual(value.zzxz,.init(2, 2, 0, 2))
        XCTAssertEqual(value.zzxw,.init(2, 2, 0, 3))
        XCTAssertEqual(value.zzyx,.init(2, 2, 1, 0))
        XCTAssertEqual(value.zzyy,.init(2, 2, 1, 1))
        XCTAssertEqual(value.zzyz,.init(2, 2, 1, 2))
        XCTAssertEqual(value.zzyw,.init(2, 2, 1, 3))
        XCTAssertEqual(value.zzzx,.init(2, 2, 2, 0))
        XCTAssertEqual(value.zzzy,.init(2, 2, 2, 1))
        XCTAssertEqual(value.zzzz,.init(2, 2, 2, 2))
        XCTAssertEqual(value.zzzw,.init(2, 2, 2, 3))
        XCTAssertEqual(value.zzwx,.init(2, 2, 3, 0))
        XCTAssertEqual(value.zzwy,.init(2, 2, 3, 1))
        XCTAssertEqual(value.zzwz,.init(2, 2, 3, 2))
        XCTAssertEqual(value.zzww,.init(2, 2, 3, 3))
        XCTAssertEqual(value.zwxx,.init(2, 3, 0, 0))
        XCTAssertEqual(value.zwxy,.init(2, 3, 0, 1))
        XCTAssertEqual(value.zwxz,.init(2, 3, 0, 2))
        XCTAssertEqual(value.zwxw,.init(2, 3, 0, 3))
        XCTAssertEqual(value.zwyx,.init(2, 3, 1, 0))
        XCTAssertEqual(value.zwyy,.init(2, 3, 1, 1))
        XCTAssertEqual(value.zwyz,.init(2, 3, 1, 2))
        XCTAssertEqual(value.zwyw,.init(2, 3, 1, 3))
        XCTAssertEqual(value.zwzx,.init(2, 3, 2, 0))
        XCTAssertEqual(value.zwzy,.init(2, 3, 2, 1))
        XCTAssertEqual(value.zwzz,.init(2, 3, 2, 2))
        XCTAssertEqual(value.zwzw,.init(2, 3, 2, 3))
        XCTAssertEqual(value.zwwx,.init(2, 3, 3, 0))
        XCTAssertEqual(value.zwwy,.init(2, 3, 3, 1))
        XCTAssertEqual(value.zwwz,.init(2, 3, 3, 2))
        XCTAssertEqual(value.zwww,.init(2, 3, 3, 3))
        XCTAssertEqual(value.wxxx,.init(3, 0, 0, 0))
        XCTAssertEqual(value.wxxy,.init(3, 0, 0, 1))
        XCTAssertEqual(value.wxxz,.init(3, 0, 0, 2))
        XCTAssertEqual(value.wxxw,.init(3, 0, 0, 3))
        XCTAssertEqual(value.wxyx,.init(3, 0, 1, 0))
        XCTAssertEqual(value.wxyy,.init(3, 0, 1, 1))
        XCTAssertEqual(value.wxyz,.init(3, 0, 1, 2))
        XCTAssertEqual(value.wxyw,.init(3, 0, 1, 3))
        XCTAssertEqual(value.wxzx,.init(3, 0, 2, 0))
        XCTAssertEqual(value.wxzy,.init(3, 0, 2, 1))
        XCTAssertEqual(value.wxzz,.init(3, 0, 2, 2))
        XCTAssertEqual(value.wxzw,.init(3, 0, 2, 3))
        XCTAssertEqual(value.wxwx,.init(3, 0, 3, 0))
        XCTAssertEqual(value.wxwy,.init(3, 0, 3, 1))
        XCTAssertEqual(value.wxwz,.init(3, 0, 3, 2))
        XCTAssertEqual(value.wxww,.init(3, 0, 3, 3))
        XCTAssertEqual(value.wyxx,.init(3, 1, 0, 0))
        XCTAssertEqual(value.wyxy,.init(3, 1, 0, 1))
        XCTAssertEqual(value.wyxz,.init(3, 1, 0, 2))
        XCTAssertEqual(value.wyxw,.init(3, 1, 0, 3))
        XCTAssertEqual(value.wyyx,.init(3, 1, 1, 0))
        XCTAssertEqual(value.wyyy,.init(3, 1, 1, 1))
        XCTAssertEqual(value.wyyz,.init(3, 1, 1, 2))
        XCTAssertEqual(value.wyyw,.init(3, 1, 1, 3))
        XCTAssertEqual(value.wyzx,.init(3, 1, 2, 0))
        XCTAssertEqual(value.wyzy,.init(3, 1, 2, 1))
        XCTAssertEqual(value.wyzz,.init(3, 1, 2, 2))
        XCTAssertEqual(value.wyzw,.init(3, 1, 2, 3))
        XCTAssertEqual(value.wywx,.init(3, 1, 3, 0))
        XCTAssertEqual(value.wywy,.init(3, 1, 3, 1))
        XCTAssertEqual(value.wywz,.init(3, 1, 3, 2))
        XCTAssertEqual(value.wyww,.init(3, 1, 3, 3))
        XCTAssertEqual(value.wzxx,.init(3, 2, 0, 0))
        XCTAssertEqual(value.wzxy,.init(3, 2, 0, 1))
        XCTAssertEqual(value.wzxz,.init(3, 2, 0, 2))
        XCTAssertEqual(value.wzxw,.init(3, 2, 0, 3))
        XCTAssertEqual(value.wzyx,.init(3, 2, 1, 0))
        XCTAssertEqual(value.wzyy,.init(3, 2, 1, 1))
        XCTAssertEqual(value.wzyz,.init(3, 2, 1, 2))
        XCTAssertEqual(value.wzyw,.init(3, 2, 1, 3))
        XCTAssertEqual(value.wzzx,.init(3, 2, 2, 0))
        XCTAssertEqual(value.wzzy,.init(3, 2, 2, 1))
        XCTAssertEqual(value.wzzz,.init(3, 2, 2, 2))
        XCTAssertEqual(value.wzzw,.init(3, 2, 2, 3))
        XCTAssertEqual(value.wzwx,.init(3, 2, 3, 0))
        XCTAssertEqual(value.wzwy,.init(3, 2, 3, 1))
        XCTAssertEqual(value.wzwz,.init(3, 2, 3, 2))
        XCTAssertEqual(value.wzww,.init(3, 2, 3, 3))
        XCTAssertEqual(value.wwxx,.init(3, 3, 0, 0))
        XCTAssertEqual(value.wwxy,.init(3, 3, 0, 1))
        XCTAssertEqual(value.wwxz,.init(3, 3, 0, 2))
        XCTAssertEqual(value.wwxw,.init(3, 3, 0, 3))
        XCTAssertEqual(value.wwyx,.init(3, 3, 1, 0))
        XCTAssertEqual(value.wwyy,.init(3, 3, 1, 1))
        XCTAssertEqual(value.wwyz,.init(3, 3, 1, 2))
        XCTAssertEqual(value.wwyw,.init(3, 3, 1, 3))
        XCTAssertEqual(value.wwzx,.init(3, 3, 2, 0))
        XCTAssertEqual(value.wwzy,.init(3, 3, 2, 1))
        XCTAssertEqual(value.wwzz,.init(3, 3, 2, 2))
        XCTAssertEqual(value.wwzw,.init(3, 3, 2, 3))
        XCTAssertEqual(value.wwwx,.init(3, 3, 3, 0))
        XCTAssertEqual(value.wwwy,.init(3, 3, 3, 1))
        XCTAssertEqual(value.wwwz,.init(3, 3, 3, 2))
        XCTAssertEqual(value.wwww,.init(3, 3, 3, 3))
    }
    
    func testSIMD4_RGBA() {
        let value = SIMD4(0, 1, 2, 3)
        XCTAssertEqual(value.rrrr,.init(0, 0, 0, 0))
        XCTAssertEqual(value.rrrg,.init(0, 0, 0, 1))
        XCTAssertEqual(value.rrrb,.init(0, 0, 0, 2))
        XCTAssertEqual(value.rrra,.init(0, 0, 0, 3))
        XCTAssertEqual(value.rrgr,.init(0, 0, 1, 0))
        XCTAssertEqual(value.rrgg,.init(0, 0, 1, 1))
        XCTAssertEqual(value.rrgb,.init(0, 0, 1, 2))
        XCTAssertEqual(value.rrga,.init(0, 0, 1, 3))
        XCTAssertEqual(value.rrbr,.init(0, 0, 2, 0))
        XCTAssertEqual(value.rrbg,.init(0, 0, 2, 1))
        XCTAssertEqual(value.rrbb,.init(0, 0, 2, 2))
        XCTAssertEqual(value.rrba,.init(0, 0, 2, 3))
        XCTAssertEqual(value.rrar,.init(0, 0, 3, 0))
        XCTAssertEqual(value.rrag,.init(0, 0, 3, 1))
        XCTAssertEqual(value.rrab,.init(0, 0, 3, 2))
        XCTAssertEqual(value.rraa,.init(0, 0, 3, 3))
        XCTAssertEqual(value.rgrr,.init(0, 1, 0, 0))
        XCTAssertEqual(value.rgrg,.init(0, 1, 0, 1))
        XCTAssertEqual(value.rgrb,.init(0, 1, 0, 2))
        XCTAssertEqual(value.rgra,.init(0, 1, 0, 3))
        XCTAssertEqual(value.rggr,.init(0, 1, 1, 0))
        XCTAssertEqual(value.rggg,.init(0, 1, 1, 1))
        XCTAssertEqual(value.rggb,.init(0, 1, 1, 2))
        XCTAssertEqual(value.rgga,.init(0, 1, 1, 3))
        XCTAssertEqual(value.rgbr,.init(0, 1, 2, 0))
        XCTAssertEqual(value.rgbg,.init(0, 1, 2, 1))
        XCTAssertEqual(value.rgbb,.init(0, 1, 2, 2))
        XCTAssertEqual(value.rgba,.init(0, 1, 2, 3))
        XCTAssertEqual(value.rgar,.init(0, 1, 3, 0))
        XCTAssertEqual(value.rgag,.init(0, 1, 3, 1))
        XCTAssertEqual(value.rgab,.init(0, 1, 3, 2))
        XCTAssertEqual(value.rgaa,.init(0, 1, 3, 3))
        XCTAssertEqual(value.rbrr,.init(0, 2, 0, 0))
        XCTAssertEqual(value.rbrg,.init(0, 2, 0, 1))
        XCTAssertEqual(value.rbrb,.init(0, 2, 0, 2))
        XCTAssertEqual(value.rbra,.init(0, 2, 0, 3))
        XCTAssertEqual(value.rbgr,.init(0, 2, 1, 0))
        XCTAssertEqual(value.rbgg,.init(0, 2, 1, 1))
        XCTAssertEqual(value.rbgb,.init(0, 2, 1, 2))
        XCTAssertEqual(value.rbga,.init(0, 2, 1, 3))
        XCTAssertEqual(value.rbbr,.init(0, 2, 2, 0))
        XCTAssertEqual(value.rbbg,.init(0, 2, 2, 1))
        XCTAssertEqual(value.rbbb,.init(0, 2, 2, 2))
        XCTAssertEqual(value.rbba,.init(0, 2, 2, 3))
        XCTAssertEqual(value.rbar,.init(0, 2, 3, 0))
        XCTAssertEqual(value.rbag,.init(0, 2, 3, 1))
        XCTAssertEqual(value.rbab,.init(0, 2, 3, 2))
        XCTAssertEqual(value.rbaa,.init(0, 2, 3, 3))
        XCTAssertEqual(value.rarr,.init(0, 3, 0, 0))
        XCTAssertEqual(value.rarg,.init(0, 3, 0, 1))
        XCTAssertEqual(value.rarb,.init(0, 3, 0, 2))
        XCTAssertEqual(value.rara,.init(0, 3, 0, 3))
        XCTAssertEqual(value.ragr,.init(0, 3, 1, 0))
        XCTAssertEqual(value.ragg,.init(0, 3, 1, 1))
        XCTAssertEqual(value.ragb,.init(0, 3, 1, 2))
        XCTAssertEqual(value.raga,.init(0, 3, 1, 3))
        XCTAssertEqual(value.rabr,.init(0, 3, 2, 0))
        XCTAssertEqual(value.rabg,.init(0, 3, 2, 1))
        XCTAssertEqual(value.rabb,.init(0, 3, 2, 2))
        XCTAssertEqual(value.raba,.init(0, 3, 2, 3))
        XCTAssertEqual(value.raar,.init(0, 3, 3, 0))
        XCTAssertEqual(value.raag,.init(0, 3, 3, 1))
        XCTAssertEqual(value.raab,.init(0, 3, 3, 2))
        XCTAssertEqual(value.raaa,.init(0, 3, 3, 3))
        XCTAssertEqual(value.grrr,.init(1, 0, 0, 0))
        XCTAssertEqual(value.grrg,.init(1, 0, 0, 1))
        XCTAssertEqual(value.grrb,.init(1, 0, 0, 2))
        XCTAssertEqual(value.grra,.init(1, 0, 0, 3))
        XCTAssertEqual(value.grgr,.init(1, 0, 1, 0))
        XCTAssertEqual(value.grgg,.init(1, 0, 1, 1))
        XCTAssertEqual(value.grgb,.init(1, 0, 1, 2))
        XCTAssertEqual(value.grga,.init(1, 0, 1, 3))
        XCTAssertEqual(value.grbr,.init(1, 0, 2, 0))
        XCTAssertEqual(value.grbg,.init(1, 0, 2, 1))
        XCTAssertEqual(value.grbb,.init(1, 0, 2, 2))
        XCTAssertEqual(value.grba,.init(1, 0, 2, 3))
        XCTAssertEqual(value.grar,.init(1, 0, 3, 0))
        XCTAssertEqual(value.grag,.init(1, 0, 3, 1))
        XCTAssertEqual(value.grab,.init(1, 0, 3, 2))
        XCTAssertEqual(value.graa,.init(1, 0, 3, 3))
        XCTAssertEqual(value.ggrr,.init(1, 1, 0, 0))
        XCTAssertEqual(value.ggrg,.init(1, 1, 0, 1))
        XCTAssertEqual(value.ggrb,.init(1, 1, 0, 2))
        XCTAssertEqual(value.ggra,.init(1, 1, 0, 3))
        XCTAssertEqual(value.gggr,.init(1, 1, 1, 0))
        XCTAssertEqual(value.gggg,.init(1, 1, 1, 1))
        XCTAssertEqual(value.gggb,.init(1, 1, 1, 2))
        XCTAssertEqual(value.ggga,.init(1, 1, 1, 3))
        XCTAssertEqual(value.ggbr,.init(1, 1, 2, 0))
        XCTAssertEqual(value.ggbg,.init(1, 1, 2, 1))
        XCTAssertEqual(value.ggbb,.init(1, 1, 2, 2))
        XCTAssertEqual(value.ggba,.init(1, 1, 2, 3))
        XCTAssertEqual(value.ggar,.init(1, 1, 3, 0))
        XCTAssertEqual(value.ggag,.init(1, 1, 3, 1))
        XCTAssertEqual(value.ggab,.init(1, 1, 3, 2))
        XCTAssertEqual(value.ggaa,.init(1, 1, 3, 3))
        XCTAssertEqual(value.gbrr,.init(1, 2, 0, 0))
        XCTAssertEqual(value.gbrg,.init(1, 2, 0, 1))
        XCTAssertEqual(value.gbrb,.init(1, 2, 0, 2))
        XCTAssertEqual(value.gbra,.init(1, 2, 0, 3))
        XCTAssertEqual(value.gbgr,.init(1, 2, 1, 0))
        XCTAssertEqual(value.gbgg,.init(1, 2, 1, 1))
        XCTAssertEqual(value.gbgb,.init(1, 2, 1, 2))
        XCTAssertEqual(value.gbga,.init(1, 2, 1, 3))
        XCTAssertEqual(value.gbbr,.init(1, 2, 2, 0))
        XCTAssertEqual(value.gbbg,.init(1, 2, 2, 1))
        XCTAssertEqual(value.gbbb,.init(1, 2, 2, 2))
        XCTAssertEqual(value.gbba,.init(1, 2, 2, 3))
        XCTAssertEqual(value.gbar,.init(1, 2, 3, 0))
        XCTAssertEqual(value.gbag,.init(1, 2, 3, 1))
        XCTAssertEqual(value.gbab,.init(1, 2, 3, 2))
        XCTAssertEqual(value.gbaa,.init(1, 2, 3, 3))
        XCTAssertEqual(value.garr,.init(1, 3, 0, 0))
        XCTAssertEqual(value.garg,.init(1, 3, 0, 1))
        XCTAssertEqual(value.garb,.init(1, 3, 0, 2))
        XCTAssertEqual(value.gara,.init(1, 3, 0, 3))
        XCTAssertEqual(value.gagr,.init(1, 3, 1, 0))
        XCTAssertEqual(value.gagg,.init(1, 3, 1, 1))
        XCTAssertEqual(value.gagb,.init(1, 3, 1, 2))
        XCTAssertEqual(value.gaga,.init(1, 3, 1, 3))
        XCTAssertEqual(value.gabr,.init(1, 3, 2, 0))
        XCTAssertEqual(value.gabg,.init(1, 3, 2, 1))
        XCTAssertEqual(value.gabb,.init(1, 3, 2, 2))
        XCTAssertEqual(value.gaba,.init(1, 3, 2, 3))
        XCTAssertEqual(value.gaar,.init(1, 3, 3, 0))
        XCTAssertEqual(value.gaag,.init(1, 3, 3, 1))
        XCTAssertEqual(value.gaab,.init(1, 3, 3, 2))
        XCTAssertEqual(value.gaaa,.init(1, 3, 3, 3))
        XCTAssertEqual(value.brrr,.init(2, 0, 0, 0))
        XCTAssertEqual(value.brrg,.init(2, 0, 0, 1))
        XCTAssertEqual(value.brrb,.init(2, 0, 0, 2))
        XCTAssertEqual(value.brra,.init(2, 0, 0, 3))
        XCTAssertEqual(value.brgr,.init(2, 0, 1, 0))
        XCTAssertEqual(value.brgg,.init(2, 0, 1, 1))
        XCTAssertEqual(value.brgb,.init(2, 0, 1, 2))
        XCTAssertEqual(value.brga,.init(2, 0, 1, 3))
        XCTAssertEqual(value.brbr,.init(2, 0, 2, 0))
        XCTAssertEqual(value.brbg,.init(2, 0, 2, 1))
        XCTAssertEqual(value.brbb,.init(2, 0, 2, 2))
        XCTAssertEqual(value.brba,.init(2, 0, 2, 3))
        XCTAssertEqual(value.brar,.init(2, 0, 3, 0))
        XCTAssertEqual(value.brag,.init(2, 0, 3, 1))
        XCTAssertEqual(value.brab,.init(2, 0, 3, 2))
        XCTAssertEqual(value.braa,.init(2, 0, 3, 3))
        XCTAssertEqual(value.bgrr,.init(2, 1, 0, 0))
        XCTAssertEqual(value.bgrg,.init(2, 1, 0, 1))
        XCTAssertEqual(value.bgrb,.init(2, 1, 0, 2))
        XCTAssertEqual(value.bgra,.init(2, 1, 0, 3))
        XCTAssertEqual(value.bggr,.init(2, 1, 1, 0))
        XCTAssertEqual(value.bggg,.init(2, 1, 1, 1))
        XCTAssertEqual(value.bggb,.init(2, 1, 1, 2))
        XCTAssertEqual(value.bgga,.init(2, 1, 1, 3))
        XCTAssertEqual(value.bgbr,.init(2, 1, 2, 0))
        XCTAssertEqual(value.bgbg,.init(2, 1, 2, 1))
        XCTAssertEqual(value.bgbb,.init(2, 1, 2, 2))
        XCTAssertEqual(value.bgba,.init(2, 1, 2, 3))
        XCTAssertEqual(value.bgar,.init(2, 1, 3, 0))
        XCTAssertEqual(value.bgag,.init(2, 1, 3, 1))
        XCTAssertEqual(value.bgab,.init(2, 1, 3, 2))
        XCTAssertEqual(value.bgaa,.init(2, 1, 3, 3))
        XCTAssertEqual(value.bbrr,.init(2, 2, 0, 0))
        XCTAssertEqual(value.bbrg,.init(2, 2, 0, 1))
        XCTAssertEqual(value.bbrb,.init(2, 2, 0, 2))
        XCTAssertEqual(value.bbra,.init(2, 2, 0, 3))
        XCTAssertEqual(value.bbgr,.init(2, 2, 1, 0))
        XCTAssertEqual(value.bbgg,.init(2, 2, 1, 1))
        XCTAssertEqual(value.bbgb,.init(2, 2, 1, 2))
        XCTAssertEqual(value.bbga,.init(2, 2, 1, 3))
        XCTAssertEqual(value.bbbr,.init(2, 2, 2, 0))
        XCTAssertEqual(value.bbbg,.init(2, 2, 2, 1))
        XCTAssertEqual(value.bbbb,.init(2, 2, 2, 2))
        XCTAssertEqual(value.bbba,.init(2, 2, 2, 3))
        XCTAssertEqual(value.bbar,.init(2, 2, 3, 0))
        XCTAssertEqual(value.bbag,.init(2, 2, 3, 1))
        XCTAssertEqual(value.bbab,.init(2, 2, 3, 2))
        XCTAssertEqual(value.bbaa,.init(2, 2, 3, 3))
        XCTAssertEqual(value.barr,.init(2, 3, 0, 0))
        XCTAssertEqual(value.barg,.init(2, 3, 0, 1))
        XCTAssertEqual(value.barb,.init(2, 3, 0, 2))
        XCTAssertEqual(value.bara,.init(2, 3, 0, 3))
        XCTAssertEqual(value.bagr,.init(2, 3, 1, 0))
        XCTAssertEqual(value.bagg,.init(2, 3, 1, 1))
        XCTAssertEqual(value.bagb,.init(2, 3, 1, 2))
        XCTAssertEqual(value.baga,.init(2, 3, 1, 3))
        XCTAssertEqual(value.babr,.init(2, 3, 2, 0))
        XCTAssertEqual(value.babg,.init(2, 3, 2, 1))
        XCTAssertEqual(value.babb,.init(2, 3, 2, 2))
        XCTAssertEqual(value.baba,.init(2, 3, 2, 3))
        XCTAssertEqual(value.baar,.init(2, 3, 3, 0))
        XCTAssertEqual(value.baag,.init(2, 3, 3, 1))
        XCTAssertEqual(value.baab,.init(2, 3, 3, 2))
        XCTAssertEqual(value.baaa,.init(2, 3, 3, 3))
        XCTAssertEqual(value.arrr,.init(3, 0, 0, 0))
        XCTAssertEqual(value.arrg,.init(3, 0, 0, 1))
        XCTAssertEqual(value.arrb,.init(3, 0, 0, 2))
        XCTAssertEqual(value.arra,.init(3, 0, 0, 3))
        XCTAssertEqual(value.argr,.init(3, 0, 1, 0))
        XCTAssertEqual(value.argg,.init(3, 0, 1, 1))
        XCTAssertEqual(value.argb,.init(3, 0, 1, 2))
        XCTAssertEqual(value.arga,.init(3, 0, 1, 3))
        XCTAssertEqual(value.arbr,.init(3, 0, 2, 0))
        XCTAssertEqual(value.arbg,.init(3, 0, 2, 1))
        XCTAssertEqual(value.arbb,.init(3, 0, 2, 2))
        XCTAssertEqual(value.arba,.init(3, 0, 2, 3))
        XCTAssertEqual(value.arar,.init(3, 0, 3, 0))
        XCTAssertEqual(value.arag,.init(3, 0, 3, 1))
        XCTAssertEqual(value.arab,.init(3, 0, 3, 2))
        XCTAssertEqual(value.araa,.init(3, 0, 3, 3))
        XCTAssertEqual(value.agrr,.init(3, 1, 0, 0))
        XCTAssertEqual(value.agrg,.init(3, 1, 0, 1))
        XCTAssertEqual(value.agrb,.init(3, 1, 0, 2))
        XCTAssertEqual(value.agra,.init(3, 1, 0, 3))
        XCTAssertEqual(value.aggr,.init(3, 1, 1, 0))
        XCTAssertEqual(value.aggg,.init(3, 1, 1, 1))
        XCTAssertEqual(value.aggb,.init(3, 1, 1, 2))
        XCTAssertEqual(value.agga,.init(3, 1, 1, 3))
        XCTAssertEqual(value.agbr,.init(3, 1, 2, 0))
        XCTAssertEqual(value.agbg,.init(3, 1, 2, 1))
        XCTAssertEqual(value.agbb,.init(3, 1, 2, 2))
        XCTAssertEqual(value.agba,.init(3, 1, 2, 3))
        XCTAssertEqual(value.agar,.init(3, 1, 3, 0))
        XCTAssertEqual(value.agag,.init(3, 1, 3, 1))
        XCTAssertEqual(value.agab,.init(3, 1, 3, 2))
        XCTAssertEqual(value.agaa,.init(3, 1, 3, 3))
        XCTAssertEqual(value.abrr,.init(3, 2, 0, 0))
        XCTAssertEqual(value.abrg,.init(3, 2, 0, 1))
        XCTAssertEqual(value.abrb,.init(3, 2, 0, 2))
        XCTAssertEqual(value.abra,.init(3, 2, 0, 3))
        XCTAssertEqual(value.abgr,.init(3, 2, 1, 0))
        XCTAssertEqual(value.abgg,.init(3, 2, 1, 1))
        XCTAssertEqual(value.abgb,.init(3, 2, 1, 2))
        XCTAssertEqual(value.abga,.init(3, 2, 1, 3))
        XCTAssertEqual(value.abbr,.init(3, 2, 2, 0))
        XCTAssertEqual(value.abbg,.init(3, 2, 2, 1))
        XCTAssertEqual(value.abbb,.init(3, 2, 2, 2))
        XCTAssertEqual(value.abba,.init(3, 2, 2, 3))
        XCTAssertEqual(value.abar,.init(3, 2, 3, 0))
        XCTAssertEqual(value.abag,.init(3, 2, 3, 1))
        XCTAssertEqual(value.abab,.init(3, 2, 3, 2))
        XCTAssertEqual(value.abaa,.init(3, 2, 3, 3))
        XCTAssertEqual(value.aarr,.init(3, 3, 0, 0))
        XCTAssertEqual(value.aarg,.init(3, 3, 0, 1))
        XCTAssertEqual(value.aarb,.init(3, 3, 0, 2))
        XCTAssertEqual(value.aara,.init(3, 3, 0, 3))
        XCTAssertEqual(value.aagr,.init(3, 3, 1, 0))
        XCTAssertEqual(value.aagg,.init(3, 3, 1, 1))
        XCTAssertEqual(value.aagb,.init(3, 3, 1, 2))
        XCTAssertEqual(value.aaga,.init(3, 3, 1, 3))
        XCTAssertEqual(value.aabr,.init(3, 3, 2, 0))
        XCTAssertEqual(value.aabg,.init(3, 3, 2, 1))
        XCTAssertEqual(value.aabb,.init(3, 3, 2, 2))
        XCTAssertEqual(value.aaba,.init(3, 3, 2, 3))
        XCTAssertEqual(value.aaar,.init(3, 3, 3, 0))
        XCTAssertEqual(value.aaag,.init(3, 3, 3, 1))
        XCTAssertEqual(value.aaab,.init(3, 3, 3, 2))
        XCTAssertEqual(value.aaaa,.init(3, 3, 3, 3))
    }
}
